//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Data;

public interface ADAOSocioEconomico <T>
{
	void Insert(T obj);
    void Update(T obj);
   
    bool SelectExiste(T obj);
    DataTable GetTabla(int id);
}

