//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Conect.DAO;
using Conect.DTO;

public class FacadeAspiranteSE :Facade
{
    IAspiranteSE a;
    public virtual void LlamarInsert(int tabla)
	{

        switch (tabla)
        {
            case 1:
                new AntecedentesAluQL().Insert(a.anteLPDTO);
                break;
            case 2:
                new ViviendaDAOSQL().Insert(a.vivienda);
                break;
            case 3:
                new IngrEgrFamiliaresDAOSQL().Insert(a.ingrEgrFamiliares);
                break;
            case 4:
                new BecasDAOSQL().Insert(a.becasYApoyos);
                break;
        }
    }
    public virtual void LlamarUpdate(int tabla)
    {

        switch (tabla)
        {
            case 1:
                new AntecedentesAluQL().Update(a.anteLPDTO);
                break;
            case 2:
                new ViviendaDAOSQL().Update(a.vivienda);
                break;
            case 3:
                new IngrEgrFamiliaresDAOSQL().Update(a.ingrEgrFamiliares);
                break;
            case 4:
                new BecasDAOSQL().Update(a.becasYApoyos);
                break;
        }
    }
    public virtual bool LlamarSelectExiste(int tabla)
    {
        bool result = false;
        switch (tabla)
        {
            case 1:
                result = (new AntecedentesAluQL()).SelectExiste(a.anteLPDTO);
                break;
            case 2:
                result = (new ViviendaDAOSQL()).SelectExiste(a.vivienda);
                break;
            case 3:
                result = (new IngrEgrFamiliaresDAOSQL()).SelectExiste(a.ingrEgrFamiliares);
                break;
            case 4:
                result = (new BecasDAOSQL()).SelectExiste(a.becasYApoyos);
                break;
        }
        return result;
    }
	public FacadeAspiranteSE(IAspiranteSE a)
	{
        this.a = a;
	}
}

