//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Conect.DTO;

public interface IAspiranteSE
{

	IngrEgrFamiliaresDTO ingrEgrFamiliares { get; }

	ViviendaDTO vivienda { get; }

    AntecedentesAluPDTO anteLPDTO { get; }

    BecasDTO becasYApoyos { get; }

}

