//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class IngrEgrFamiliaresDTO
{
	public virtual double ief_Padre
	{
		get;
		set;
	}
	public virtual double ief_Madre
	{
		get;
		set;
	}
	public virtual double ief_Usted
	{
		get;
		set;
	}
	public virtual double ief_Hermanos
	{
		get;
		set;
	}
	public virtual double ief_Conyugue
	{
		get;
		set;
	}
	public virtual double ief_Otros
	{
		get;
		set;
	}
	public virtual double ief_Total
	{
		get;
		set;
	}
	public virtual double ief_Renta
	{
		get;
		set;
	}
	public virtual double ief_Alimentacion
	{
		get;
		set;
	}
	public virtual double ief_Vestido
	{
		get;
		set;
	}
	public virtual double ief_Transporte
	{
		get;
		set;
	}
	public virtual double ief_Colegiaura
	{
		get;
		set;
	}
	public virtual double ief_Agua
	{
		get;
		set;
	}
	public virtual double ief_Electricidad
	{
		get;
		set;
	}
	public virtual double ief_GasCombustible
	{
		get;
		set;
	}
	public virtual double ief_Telefono
	{
		get;
		set;
	}
    public virtual double ief_OtrosE
    {
        get;
        set;
    }
    public virtual double ief_TotalEgresos
	{
		get;
		set;
	}
    public string ief_ParentezcoPersona { get; set; }
    public double ief_CantidadPersona { get; set; }
    public string ief_FrecuenciaAporte { get; set; }
    public double ief_GastoDiario { get; set; }
    public string ief_Conceptos { get; set; }
    public virtual int alu_ID
	{
		get;
		set;
	}
}

