//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ViviendaDTO
{
	public virtual string viv_MaterialTecho
	{
		get;
		set;
	}
	public virtual string viv_MaterialParedes
	{
		get;
		set;
	}
	public virtual string viv_MaterialPiso
	{
		get;
		set;
	}
	public virtual string viv_CocinaIndependiente
	{
		get;
		set;
	}
	public virtual int viv_NoCuartos
	{
		get;
		set;
	}
	public virtual int viv_NoDormitorios
	{
		get;
		set;
    }
    public virtual string viv_TipoVivienda
    {
        get;
        set;
    }
    public virtual int alu_ID
    {
        get;
        set;
    }
	public virtual bool viv_Lavadora
	{
		get;
		set;
	}
	public virtual bool viv_Cisterna
	{
		get;
		set;
	}
    public virtual bool viv_Drenaje
    {
        get;
        set;
    }
    public virtual bool viv_Compu
    {
        get;
        set;
    }
    public virtual bool viv_AcceInter
    {
        get;
        set;
    }
    public virtual bool viv_Auto
    {
        get;
        set;
    }
    public virtual bool viv_Moto
    {
        get;
        set;
    }
    public virtual bool viv_Horno
    {
        get;
        set;
    }
    public virtual bool viv_Electrodomes
    {
        get;
        set;
    }
    public virtual bool viv_Regadera
    {
        get;
        set;
    }
    public virtual bool viv_MedLuz
    {
        get;
        set;
    }
    public virtual bool viv_Dvd
    {
        get;
        set;
    }
    public virtual bool viv_Radio
    {
        get;
        set;
    }
    public virtual bool viv_TV
    {
        get;
        set;
    }
    public string viv_MedioTransporte { get; set; }
    public bool viv_Television { get; set; }
    public bool viv_Gas { get; set; }
    public string viv_TiempoTraslado { get; set; }
    public bool viv_Luz { get; set; }
    public bool viv_AguaPotable { get; set; }
    public bool viv_EstufaDeGas { get; set; }
    public bool viv_TinacoAgua { get; set; }
    public virtual bool viv_Refrigerador
	{
		get;
		set;
	}
    public bool viv_Telefono { get; set; }
    public string viv_LugarProcedencia { get; set; }
    public double viv_GastoPasaje { get; set; }
}

